### ISSUE TITLE
logout when release ECSMinion object

### ISSUE THREAD

**Issue by MingatRubicon** [chadlung/ecsminion#1]
curren ECSMinion object will keep a token and the token can be reused between sessions. it need a logout feature so that caller can explicitly logout and invalidate the token.

**Comment by chadlung** [comment]
This is available here:
https://github.com/chadlung/ecsminion/blob/99cd8f8cf64a0e514eff73abc26b07ebc08884b8/ecsminion/api/authentication.py#L9-L35
